### ISSUE TITLE
Add Power command (was: Droplet actions)

### ISSUE THREAD

**Issue by booyaa** [masayukioguni/godo-cli#25]
I would like to add more functionality to godo-cli. 

I need the ability to shutdown and snapshot a droplet. 

Before I start, I would like to check it's okay to create two new commands in the command folder called shutdown.go and snapshot.go.

If you are happy for me to do this, I'll create a new fork of your project with new branch called shutdown_snapshot.

I will wait for your feedback, in case you propose a different structure.

**Comment by masayukioguni** [comment]
Thanks. I welcome your pull request.

**Comment by booyaa** [comment]
Oguni-san, after thinking about this more I've decided decided to implement a power command first. Which will allow you to power off, on or cycle a droplet. I will raise separate issues for the shutdown and snapshot commands. I hope this is okay? I will send the pull request now.

**Comment by booyaa** [comment]
Implemented through e5217b3ea5c65d69519fc9817fc40d44101771a8
