### ISSUE TITLE
Enhance the info command

### ISSUE THREAD

**Issue by booyaa** [masayukioguni/godo-cli#33]
Oguni-san,

Do you think the `info` command would be more helpful if it displayed the history for the droplet?

At the moment it displays this information:

```
status: %s, region :%s, id: %d, image id:%d size:%s
```

Which is not to dissimilar to the `droplets` command.

With the enhancement, it could look like this:

```
status: %s, region :%s, id: %d, image id:%d size:%s

droplet history:
id       | status    | type     | start                | finish
36805187 | completed | snapshot | 2014-11-14T16:37:34Z | 2014-11-14T16:39:32Z
```

Let me know if you think this is a good idea.

**Comment by masayukioguni** [comment]
:+1: 
I think a very good idea .
