### ISSUE TITLE
Added DomainsCommand but getting error

### ISSUE THREAD

**Issue by rodolfobandeira** [masayukioguni/godo-cli#42]
Hi There!

I tried to replicate the same idea from DropletsCommand but I'm getting error when I try to compile.
`src/github.com/rodolfobandeira/godo-cli/main.go:93: undefined: command.DomainsCommand`

Do you have any idea how to solve it?
The actual code is here: [https://github.com/rodolfobandeira/godo-cli/blob/master/command/domains.go](https://github.com/rodolfobandeira/godo-cli/blob/master/command/domains.go)

Thank you

**Comment by masayukioguni** [comment]
Thank you for contacting

https://github.com/rodolfobandeira/godo-cli/pull/2
